#!/usr/bin/python

import sys
import pylab as pl
import gaze.utils as gu

if __name__ == '__main__':
    # get input and output filenames
    in_file, out_file = sys.argv[1:3]

    data = gu.load_data(in_file)
    print "Loaded %i samples" % len(data)

    filtered_data = gu.filter_data(data)
    print "Removed %i samples" % (len(data) -  len(filtered_data))

    fig = gu.make_heatmap_plot(filtered_data[:, 1], filtered_data[:, 2])
    pl.savefig(out_file)
